intent_parameters:
  data_fetch:
    critical:
      - name: "entity_type"
        type: "str"
        description: "Type of financial entity (assets, liabilities, savings, income, expenses, stocks, insurance, goals, financial_summary)"
    optional:
      - name: "time_period"
        type: "str"
        description: "Time range for data (last_month, last_3_months, this_year, specific_date, etc.)"
      - name: "category"
        type: "str"
        description: "Category filter (real_estate, vehicles, loans, credit_cards, etc.)"
      - name: "subcategory"
        type: "str"
        description: "Subcategory filter (groceries, entertainment, transportation, etc.)"
      - name: "type"
        type: "str"
        description: "Type filter (checking, savings, mortgage, health_insurance, etc.)"
      - name: "provider"
        type: "str"
        description: "Provider filter (bank names, insurance companies, etc.)"
      - name: "name"
        type: "str"
        description: "Name filter for specific entities"
      - name: "source"
        type: "str"
        description: "Income source filter (salary, freelance, investment, etc.)"
      - name: "frequency"
        type: "str"
        description: "Frequency filter (monthly, quarterly, yearly)"
      - name: "payment_method"
        type: "str"
        description: "Payment method filter (credit_card, cash, bank_transfer, etc.)"
      - name: "priority"
        type: "str"
        description: "Priority filter (low, medium, high)"
      - name: "min_amount"
        type: "int"
        description: "Minimum amount filter (in cents)"
        constraints: {"ge": 0}
      - name: "max_amount"
        type: "int"
        description: "Maximum amount filter (in cents)"
        constraints: {"ge": 0}
      - name: "min_premium"
        type: "int"
        description: "Minimum premium filter for insurance (in cents)"
        constraints: {"ge": 0}
      - name: "max_premium"
        type: "int"
        description: "Maximum premium filter for insurance (in cents)"
        constraints: {"ge": 0}
      - name: "min_coverage"
        type: "int"
        description: "Minimum coverage filter for insurance (in cents)"
        constraints: {"ge": 0}
      - name: "max_coverage"
        type: "int"
        description: "Maximum coverage filter for insurance (in cents)"
        constraints: {"ge": 0}
      - name: "min_current_value"
        type: "int"
        description: "Minimum current value filter for assets/stocks (in cents)"
        constraints: {"ge": 0}
      - name: "max_current_value"
        type: "int"
        description: "Maximum current value filter for assets/stocks (in cents)"
        constraints: {"ge": 0}
      - name: "min_target"
        type: "int"
        description: "Minimum target filter for goals (in cents)"
        constraints: {"ge": 0}
      - name: "max_target"
        type: "int"
        description: "Maximum target filter for goals (in cents)"
        constraints: {"ge": 0}
      - name: "start_date"
        type: "datetime"
        description: "Start date filter"
      - name: "end_date"
        type: "datetime"
        description: "End date filter"
      - name: "limit"
        type: "int"
        description: "Maximum number of records to return"
        constraints: {"ge": 1, "le": 1000}
      - name: "offset"
        type: "int"
        description: "Number of records to skip for pagination"
        constraints: {"ge": 0}
      - name: "order_by"
        type: "str"
        description: "Field to sort results by (name, amount, date, etc.)"
      - name: "order_direction"
        type: "str"
        description: "Sort order (asc, desc)"
        constraints: {"pattern": "^(asc|desc)$"}
      - name: "entity_id"
        type: "str"
        description: "Specific entity ID for single record queries"
    description: "Retrieve and display financial data from various entity types"

  aggregate:
    critical:
      - name: "metric_type"
        type: "str"
        description: "Type of metric to calculate (sum, average, count, summary, etc.)"
    optional:
      - name: "group_by"
        type: "str"
        description: "Field to group results by (category, type, provider, etc.)"
      - name: "time_period"
        type: "str"
        description: "Time range for aggregation"
      - name: "category_filter"
        type: "List[str]"
        description: "Categories to include in aggregation"
      - name: "entity_filter"
        type: "List[str]"
        description: "Entity types to include in aggregation"
      - name: "amount_range"
        type: "List[int]"
        description: "Amount range filter [min, max] in cents"
    description: "Analyze and summarize financial data across different entity types"

  action:
    critical:
      - name: "action_type"
        type: "str"
        description: "Type of action to perform (create, update, delete, transfer, etc.)"
    optional:
      - name: "amount"
        type: "int"
        description: "Amount for the action (in cents)"
        constraints: {"ge": 0}
      - name: "entity_type"
        type: "str"
        description: "Type of entity for the action (asset, liability, savings, income, expense, stock, insurance, goal)"
      - name: "entity_id"
        type: "str"
        description: "Specific entity ID for update/delete operations"
      - name: "name"
        type: "str"
        description: "Name for the entity"
      - name: "category"
        type: "str"
        description: "Category for the entity"
      - name: "subcategory"
        type: "str"
        description: "Subcategory for the entity"
      - name: "type"
        type: "str"
        description: "Type for the entity"
      - name: "provider"
        type: "str"
        description: "Provider for the entity"
      - name: "source"
        type: "str"
        description: "Source for income"
      - name: "frequency"
        type: "str"
        description: "Frequency for income"
      - name: "payment_method"
        type: "str"
        description: "Payment method for expenses"
      - name: "priority"
        type: "str"
        description: "Priority for goals"
      - name: "description"
        type: "str"
        description: "Description of the entity or action"
      - name: "date"
        type: "datetime"
        description: "Date for the entity"
      - name: "start_date"
        type: "datetime"
        description: "Start date for the entity"
      - name: "end_date"
        type: "datetime"
        description: "End date for the entity"
      - name: "target_date"
        type: "datetime"
        description: "Target date for goals"
      - name: "current_value"
        type: "int"
        description: "Current value for assets/stocks (in cents)"
      - name: "purchase_value"
        type: "int"
        description: "Purchase value for assets (in cents)"
      - name: "purchase_date"
        type: "datetime"
        description: "Purchase date for assets/stocks"
      - name: "returns"
        type: "float"
        description: "Returns percentage for stocks"
      - name: "premium"
        type: "int"
        description: "Premium for insurance (in cents)"
      - name: "coverage"
        type: "int"
        description: "Coverage for insurance (in cents)"
      - name: "policy_number"
        type: "str"
        description: "Policy number for insurance"
      - name: "current_balance"
        type: "int"
        description: "Current balance for savings (in cents)"
      - name: "interest_rate"
        type: "float"
        description: "Interest rate for savings/liabilities"
      - name: "maturity_date"
        type: "datetime"
        description: "Maturity date for savings"
      - name: "monthly_contribution"
        type: "int"
        description: "Monthly contribution for savings (in cents)"
      - name: "target_amount"
        type: "int"
        description: "Target amount for savings/goals (in cents)"
      - name: "emi"
        type: "int"
        description: "EMI for liabilities (in cents)"
      - name: "target"
        type: "int"
        description: "Target amount for goals (in cents)"
      - name: "current"
        type: "int"
        description: "Current amount for goals (in cents)"
    description: "Execute financial operations and manage financial entities"

  unknown:
    critical: []
    optional: []
    description: "Intent not clearly determined"

  clarification:
    critical: []
    optional: []
    description: "Request for additional information or clarification" 